apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: default
  labels:
    app: spring-petclinic
spec:
  replicas: 3  # 3개의 레플리카 설정
  selector:
    matchLabels:
      app: spring-petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1    # 기존 파드 중 하나를 종료한 후 새 파드생성 (파드 3개 유지)
      maxSurge: 0          # 새로운 파드 추가 X
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: ksy99/spring-petclinic-prometheus:latest  # Docker Hub에 업로드된 이미지
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45  # 컨테이너 시작 후 5초 대기 후 첫 프로브 실행
          periodSeconds: 10         # 10초마다 프로브 실행
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: default
  labels:
    app: spring-petclinic
spec:
  type: LoadBalancer  # 외부 접근을 위한 LoadBalancer 설정
  selector:
    app: spring-petclinic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
